name: Bruno CI Workflow Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"  # Every Monday at 00:00 UTC
    - cron: "0 0 * * 5"  # Every Friday at 00:00 UTC
  workflow_dispatch:

jobs:
  BrunoAPI:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Bru CLI from NPM
        run: npm install -g @usebruno/cli
  
      - name: Display Bru CLI Version
        run: bru --version

      - name: Install dependencies
        run: npm install
        working-directory: ./API

      - name: Run booksAPI tests
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npm run booksAPI
        working-directory: ./API

      - name: Create results directory
        if: always()
        run: mkdir -p API/results

      - name: Move index.html results file to results directory
        if: always()
        run: mv API/index.html API/results/index.html
          
      - name: Sanitize report
        if: always()
        run: node sanitizeReport.js
        working-directory: ./API

      - name: Deploy the report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: API/results
          publish_branch: gh-pages

      - name: Upload test results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: API/results/index.html
          retention-days: 3
